### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by dikshajoshi18**

### CODE REVIEW

**Review by aashutosh-agrawal — COMMENTED** [review]
Please add only the function code (preferably your own implementation) which is neatly written, can be easily understood and that can be used as a code snippet in contests. 
see [this](https://github.com/aashutosh-agrawal/Competitive_Programming/blob/master/Bucket%20Sort.txt) for reference.

**Comment by dikshajoshi18** [comment]
please check it now

**Review by aashutosh-agrawal — APPROVED** [review]
It is still single source Dijkstra's Algorithm. Make it Multi-Source.
But the code is really good and hence, you deserve a reward for this. I am merging this PR for the good implementation of Single source Dijkstra. And you can make another PR for multi source Dijkstra. ;)

**Comment by aashutosh-agrawal** [comment]
Thank you for the contribution.
Please fill the merged [PR form](https://docs.google.com/forms/d/e/1FAIpQLSexn0dft5QJtLvyGr7ME4-cmbYFCZW0jLNQ9bAIaQXF_YFoKQ/viewform) So that we may count this for the contest.

**Pull request merged**
