### PR TITLE
Boruvka's algorithm

### PR DESCRIPTION
**Pull request by arsalanhub**

### CODE REVIEW

**Comment by aashutosh-agrawal** [comment]
This code snippet is incomplete and would not serve the purpose.

**Comment by arsalanhub** [comment]
This code is missing declaration part of graph. In my other PR you told to only write function part.

Should I include declaration part?

**Comment by aashutosh-agrawal** [comment]
I have instructed to not use the template and only add the required functions, but the code must be complete and able to work. 
This piece of code is lacking the structs that it is using in the functions. 
Also declaration is not required if it is rearranged properly.

But there is the same implementation on GFG. Try to do your own implementation which is neatly written, can be easily understood and that can be used as a code snippet in contests. 

Also, change the function to return the tree (as a vector or pairs) instead of printing it.

**Comment by manav014** [comment]
@arsalanhub     Please update either you are working on this PR or not as we have to close it before the end of the contest.

**Comment by arsalanhub** [comment]
You can close.

**Comment by manav014** [comment]
Thank you for this PR, I am closing it.

**Pull request closed without merging**
