### PR TITLE
Added Bucket Sort with practice problem

### PR DESCRIPTION
**Pull request by arsalanhub**

### CODE REVIEW

**Review by aashutosh-agrawal — CHANGES_REQUESTED** [review]
Please make the following changes:

1. Remove the template and only keep the bucketSort function (so that it can be easily used as a snippet without much clutter)
2. Remove the unnecessary comments (You can just add a link to the algorithm from gfg in a comment)

**Comment by arsalanhub** [comment]
Made the changes

**Review by aashutosh-agrawal — CHANGES_REQUESTED** [review]
Looks good. 
Remove the first two lines also(include and using) because the code that will use this piece of code as a snippet will already have a include and using namespace line.

**Comment by arsalanhub** [comment]
done

**Comment by aashutosh-agrawal** [comment]
Well, Thank you for the changes. Welcome aboard.
I am merging this PR please fill the [merged PR](https://docs.google.com/forms/d/e/1FAIpQLSexn0dft5QJtLvyGr7ME4-cmbYFCZW0jLNQ9bAIaQXF_YFoKQ/viewform) form So that we may count this for the contest.

**Pull request merged**
