### PR TITLE
added Deletion_Alternate_Node in Sll and Tetrahedral numbers Series

### PR DESCRIPTION
**Pull request by Tejaswika**

### CODE REVIEW

**Comment by aashutosh-agrawal** [comment]
Appreciate the effort of finding topics and bringing them here. But I think Linked List is a topic which already has the best implementation on GFG. So I would not consider merging Linked List programs in my repo.

For the tetrahedral number series, it can be considered if you make the following changes:
1. Make a function that calculates and returns the n'th tetrahedral number in the series.
2. Make a function that calculates and returns the sum upto n'th tetrahedral numbers.
3. Make a function that calculates and returns the sum from l'th to r'th tetrahedral numbers in the series.

Always calculate and return modulo mod (a global variable). See [this](https://github.com/aashutosh-agrawal/Competitive_Programming/blob/master/DoubleTowerOfHanoi.txt) for reference.

**Review by aashutosh-agrawal — COMMENTED** [review]
Please read the requirements carefully.
You are required to make a function that returns the sum of a range starting from l'th term and ending at r'th term ( l, l + 1, . . . , r -1, r ) of the tetrahedral series.
Also, you can do better than O(n) for finding the sum upto n'th term. (it can be done in O(1) ).
And you have to return all the values modulo mod.

**Comment by manav014** [comment]
@Tejaswika  Please update either you are working on this PR or not as we have to close it before the end of the contest.

**Comment by Tejaswika** [comment]
Sir, you can close the PR, cause I can't modify it further

**Comment by manav014** [comment]
Okay sure Thank you for this PR

**Pull request closed without merging**
